### ISSUE TITLE
Multi-Word Right Shift Emits Bad C++ Code

### ISSUE THREAD

**Issue by palmer-dabbelt** [ucb-bar/chisel#229]
When building some Chisel code from my torture tester, I get the following error message:

```
./Torture.cpp: In member function 'virtual void Torture_t::clock_lo(dat_t<1>)':
./Torture.cpp:66:101: error: no match for 'operator[]' in '((Torture_t*)this)->T
orture_t::Torture__io_in0[(((((__w + 1ul) ^ 1ul) & ((val_t)(-(__w == 18446744073
709551615ul)))) ^ 1ul) & ((val_t)(-((((__w + 1ul) ^ 1ul) & ((val_t)(-(__w == 184
46744073709551615ul)))) != 1ul))))]'
./Torture.cpp:66:232: error: no match for 'operator[]' in '((Torture_t*)this)->T
orture_t::Torture__io_in0[((((__w ^ 1ul) & ((val_t)(-(__w == 0ul)))) ^ 1ul) & ((
val_t)(-(((__w ^ 1ul) & ((val_t)(-(__w == 0ul)))) != 1ul))))]'
```

I've bisected the problem down to a single, fairly large commit

```
commit e6203e5420521c7adebc86ca7a251c3ba0633e6b
Author: Andrew Waterman <waterman@eecs.berkeley.edu>
Date:   Sun May 25 17:43:24 2014 -0700

    Improve C++ code generation
```

Here's the "git bisect" script that I used to track down the error, which also includes the source code

```
#!/bin/bash

sbt publish-local || exit 125

TMP=`mktemp -d -t bisect.XXXXXX`
trap "rm -rf $TMP* 2>/dev/null" EXIT

cp target/scala-*/chisel_*-SNAPSHOT.jar $TMP/chisel.jar

cd $TMP

cat >Torture.scala <<"EOF"
import Chisel._;
object Torture {
  def main(args: Array[String]): Unit = {
    chiselMain(args, () => Module(new Torture()));
  }
}
class Torture extends Module {
  class IO extends Bundle {
    val in0 = Bits(INPUT, width=128);
    val out0 = Bits(OUTPUT, width=32);
  }
  val io = new IO();
  val io_in0 = Bits(width = 128);
  io_in0 := io.in0;
  val Torture1 = Bits(width = 32);
  Torture1 := (UInt(io_in0) >> UInt(0)).toBits;
  io.out0 := Torture1;
}
EOF

scalac -classpath chisel.jar:. Torture.scala
scala -classpath chisel.jar:. Torture --vcd --backend c --genHarness --compile

if test -x Torture
then
    echo "Success"
    exit 0
else
    echo "Failure"
    exit 1
fi
```
