### PR TITLE
Fixed Point data type that extends Bits with Num[Fixed]

### PR DESCRIPTION
**Pull request by djmmoss**
This is a fixed point data type that allows basic math operations between variables with the same fractional width. The data type supports two basic variations of multiplication, one using truncation and the other with rounding. A fixed test suite is included.

### CODE REVIEW

**Comment by ucbjrl** [comment]
This fails for me with:

    [error] /scratch/ucbjrl/ucb-bar/chisel/src/main/scala/Fixed.scala:57: class Fixed needs to be abstract, since method % in trait Num of type (b: Chisel.Fixed)Chisel.Fixed is not defined
    [error] (Note that T does not match Chisel.Bits)
    [error] class Fixed(var fractionalWidth : Int = 0) extends Bits with Num[Fixed] {
    [error]       ^
    [error] one error found
    [error] (compile:compile) Compilation failed

**Comment by djmmoss** [comment]
Sorry about that, I merge the lastest ucb-bar/chisel into our branch and updated the code.

**Comment by ucbjrl** [comment]
Unfortunately, this fails to compile in Scala 2.11 with:

    [error] /scratch/ucbjrl/ucb-bar/chisel/src/main/scala/ChiselUtil.scala:141: in object ShiftRegister, multiple overloaded alternatives of method apply define default arguments.
    [error] object ShiftRegister
    [error]        ^

It's possible some minor surgery would allow merging the apply() methods. Check UInt.scala for its resolution of the same issue.

**Comment by djmmoss** [comment]
Thanks for the quickly reply, I updated the ShiftRegister code and tested it with 2.11.5.

**Comment by ucbjrl** [comment]
Resolved with pr #454
